import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../../styles/Home.module.css';
import { posts, post, blocks } from '../../lib/notion';
import Link from 'next/link';
import Layout from '../../components/Layout';
import utilStyles from '../../styles/utils.module.css';

export async function getServerSideProps() {
    let { results } = await posts();
    return {
        props: {
            posts: results,
        },
    };
}

interface Props {
    posts: [any];
}

const Post: NextPage<Props> = (props) => {
    return (
        <div className={styles.container}>
            <Head>
                <title>ビビッとのBlog</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/images/bibitto_icon.jpeg" />
            </Head>

            <Layout>
                <section className={utilStyles.headingMd}>
                    <div className="grid gap-10 md:grid-cols-3 grid-cols-2 grid-rows-3">
                        {props.posts.map((result, index) => {
                            return (
                                <article key={index}>
                                    <div className="rounded-b-lg shadow hover:shadow-indigo-500/40">
                                        <Link href={`/posts/${result.id}`}>
                                            {/* 画像部分でポインターにならない */}
                                            <Image
                                                className="rounded-t-lg"
                                                src={result.properties.thumbnail.files[0].file.url}
                                                alt="thumbnail"
                                                height={300}
                                                width={400}
                                            />
                                        </Link>
                                        <Link href={`/posts/${result.id}`}>
                                            <p className="text-center font-bold">
                                                {result.properties.post.title[0].plain_text}
                                            </p>
                                        </Link>
                                        <small className="text-zinc-400">{result.properties.date.date.start}</small>
                                    </div>
                                </article>
                            );
                        })}
                    </div>
                </section>

                <Link href="/">Homeに戻る</Link>
            </Layout>
        </div>
    );
};

export default Post;
