import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import { posts } from '../../lib/notion';
import Link from 'next/link';
import Layout from '../../components/Layout';

export async function getServerSideProps() {
    let { results } = await posts();
    return {
        props: {
            posts: results,
        },
    };
}

interface Props {
    posts: [any];
}

const Post: NextPage<Props> = (props) => {
    return (
        <div>
            <Head>
                <title>ビビッとのBlog</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/images/bibitto_icon.jpeg" />
            </Head>

            <Layout>
                <section>
                    <div className="grid gap-10 md:grid-cols-3 sm:grid-cols-2 grid-cols-1 grid-rows-3">
                        {props.posts.map((result, index) => {
                            return (
                                <article key={index}>
                                    <div className="border-2 rounded-lg shadow hover:shadow-indigo-500/40 text-center hover:opacity-50 cursor-pointer">
                                        <Link href={`/posts/${result.id}`}>
                                            <Image
                                                className="rounded-t"
                                                src={result.properties.thumbnail.files[0].file.url}
                                                alt="thumbnail"
                                                height={550}
                                                width={700}
                                            />
                                        </Link>
                                        <Link href={`/posts/${result.id}`}>
                                            <p className="font-bold">{result.properties.post.title[0].plain_text}</p>
                                        </Link>
                                        <small className="text-zinc-400">{result.properties.date.date.start}</small>
                                    </div>
                                </article>
                            );
                        })}
                    </div>
                </section>
            </Layout>
        </div>
    );
};

export default Post;
