import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import {posts} from '../lib/notion';
import Link from 'next/link';
import Layout from '../components/Layout';
import utilStyles from'../styles/utils.module.css'

export async function getServerSideProps() {
  // Get the posts
  let { results } = await posts();
  // Return the result
  return {
    props: {
      posts: results
    }
  }
};

interface Props {
  posts: [any]
};


const Home: NextPage<Props> = (props) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>

        <section className={utilStyles.headingMd}>
          <p>
            こんにちは、ビビッとです！
          </p>
        </section>

        <section className={utilStyles.headingMd}>
          <h2>📝エンジニアのブログ</h2>
          <div className={styles.grid}>
            {
              props.posts.map((result,index) => {
                console.log(result)
              return (
                <article key={index}>
                  <Link href='/posts/firstPost'>
                    <Image src={result.properties.thumbnail.files[0].file.url} alt='thumbnail' height={400} width={600}/>
                  </Link>
                  <Link href="/posts/firstPost">
                    <a className={utilStyles.boldText}>{result.properties.post.title[0].plain_text}</a>
                  </Link>
                  <br/>
                  <small className={utilStyles.lightText}>
                    {result.properties.date.date.start}
                  </small>                    
                </article>
                )
              })
            }
          </div>
        </section>
      </Layout>



      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
function databaseId(databaseId: any, arg1: string) {
  throw new Error('Function not implemented.')
}

